# This is a basic workflow to help you get started with Actions

name: CI ON EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  deploy:
    environment: DEV
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
   
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Run tests
      run: npm test

    - name: Prepare SSH Key
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.ppk
          chmod 600 key.ppk  
          
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOSTNAME: ${{ secrets.EC2_HOST }}
        USER_NAME: ${{ secrets.EC2_USERNAME }}
        
      run: |
        # sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        # sudo chmod 700 /root/.ssh
        # sudo chmod 600 /root/.ssh/authorized_keys
        # echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -i key.pem -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
        cd ~/nestjs-hello-world &&
        git pull origin main &&
        npm install &&
        npm run build &&
        pm2 restart dist/main.js
        '
      

